dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - scikit-image
    - matplotlib
    - pandas
    - thinc
    - opencv-python
    - pillow
